import "./globals.css";
import Navbar from "@/components/Navbar";

import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";

import AuthProvider from "@/context/AuthProvider";
import { LivestockProvider } from "@/context/LivestockContext";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata = {
  title: "PetsKart ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <LivestockProvider>
            <Navbar />
            <Toaster />
            {children}

            <Footer />
          </LivestockProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
